apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: longhorn-ui-external-secret
  namespace: longhorn-system
spec:
  organizationId: 4f7f686d-bd5a-4fe5-8b27-b1b3000f631d
  secretName: basic-auth
  map:
    - bwSecretId: db45b3c0-0ef4-4c2f-8d24-b1b5017df5b6
      secretKeyName: auth
  authToken:
    secretName: bitwarden-access-token
    secretKey: token
