apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/description: MongoDB Cluster IP
  name: mongodb-clusterip
spec:
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 30017
  selector:
    app: mongodb
  type: NodePort
