apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-prod-tls
spec:
  secretName: wildcard-cert-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.rossreicks.com"
  dnsNames:
    - "*.rossreicks.com"
