version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: America/Chicago
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - /config/pihole/etc-pihole:/etc/pihole
      - /config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: favonia/cloudflare-ddns:latest
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=home.rossreicks.com
      - PROXIED=false
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400
    restart: unless-stopped

  # backup ui
  backrest:
      image: garethgeorge/backrest:latest
      container_name: backrest
      volumes:
        - /config/backrest/data:/data
        - /config/backrest/config:/config
        - /config/backrest/cache:/cache
        - /datapool/backups/repos:/repos
      environment:
        - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
        - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
        - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
        - TZ=America/Chicago # set the timezone for the container, used as the timezone for cron jobs.
      restart: unless-stopped
      ports:
        - 9898:9898
