version: "3.8"
services:
    overseerr:
        image: lscr.io/linuxserver/overseerr:latest
        container_name: overseerr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /config/overseerr:/config
        ports:
            - 5055:5055
        restart: unless-stopped

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - VERSION=docker
        volumes:
            - /config/prowlarr:/config
        ports:
            - 9696:9696
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - VERSION=docker
        volumes:
            - /config/radarr:/config
            - /datapool/media/downloads:/downloads
            - /datapool/media/media/movies:/movies
        ports:
            - 7878:7878
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - VERSION=docker
        volumes:
            - /config/sonarr:/config
            - /datapool/media/downloads:/downloads
            - /datapool/media/media/tv:/tv
        ports:
            - 8989:8989
        restart: unless-stopped

    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /config/bazarr:/config
            - /datapool/media/media/movies:/movies
            - /datapool/media/media/tv:/tv
        ports:
            - 6767:6767
        restart: unless-stopped

    nzbget:
        image: lscr.io/linuxserver/nzbget:latest
        container_name: nzbget
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - NZBGET_USER=${NZBGET_USER}
            - NZBGET_PASS=${NZBGET_PASS}
        volumes:
            - /config/nzbget:/config
            - /datapool/media/downloads:/downloads
        ports:
            - 6789:6789 # conflicts with prowlarr
        restart: unless-stopped

    mkvpriority:
        image: ghcr.io/kennethsible/mkvpriority
        container_name: mkvpriority
        user: 1000:1000
        volumes:
            - /datapool/media/media:/media
            - /config/mkvpriority:/config
        restart: unless-stopped
# networks:
#     web:
#     internal: # used for things not exposed to the internet
