version: "3.8"
services:
    overseerr:
        image: lscr.io/linuxserver/overseerr:latest
        container_name: overseerr
        networks:
            - web
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /config/overseerr:/config
        ports:
            - 5055:5055
        restart: unless-stopped

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        networks:
            - web
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - VERSION=docker
        volumes:
            - /config/prowlarr:/config
        ports:
            - 9696:9696
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        networks:
            - web
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - VERSION=docker
        volumes:
            - /config/radarr:/config
            - /datapool/media/downloads:/downloads
            - /datapool/media/media/movies:/movies
        ports:
            - 7878:7878
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        networks:
            - web
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - VERSION=docker
        volumes:
            - /config/sonarr:/config
            - /datapool/media/downloads:/downloads
            - /datapool/media/media/tv:/tv
        ports:
            - 8989:8989
        restart: unless-stopped

    nzbget:
        image: lscr.io/linuxserver/nzbget:latest
        container_name: nzbget
        networks:
            - web
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /config/nzbget:/config
            - /datapool/media/downloads:/downloads
        ports:
            - 9696:9696
        restart: unless-stopped

networks:
    web:
    internal: # used for things not exposed to the internet
