apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdns
  labels:
    app: duckdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duckdns
  template:
    metadata:
      labels:
        app: duckdns
    spec:
      containers:
      - name: duckdns
        image: linuxserver/duckdns:latest
        env:
        - name: SUBDOMAINS
          value: "rossreicks"
        - name: TZ
          value: "America/Chicago"
        envFrom:
          - secretRef:
              name: duckdns-secret
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: duckdns-secret
spec:
  organizationId: 4f7f686d-bd5a-4fe5-8b27-b1b3000f631d
  secretName: duckdns-secret
  map:
    - bwSecretId: 79293dac-9eed-4f10-a996-b1ba0018a7c3
      secretKeyName: TOKEN
  authToken:
    secretName: bitwarden-access-token
    secretKey: token
