apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  ports:
  - name: radarr
    port: 80
    targetPort: 7878
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: radarr.rossreicks.com
    external-dns.alpha.kubernetes.io/target: rossreicks.duckdns.org
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - radarr.rossreicks.com
    secretName: wildcard-cert-prod-tls
  rules:
    - host: radarr.rossreicks.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: radarr
subsets:
- addresses:
  - ip: 192.168.1.200
  ports:
  - name: radarr
    port: 7878
    protocol: TCP
