domain: rossreicks.com
services:
  - name: radarr
    ip: 192.168.1.200
    port: 7878
  - name: prowlarr
    ip: 192.168.1.200
    port: 9696
  - name: sonarr
    ip: 192.168.1.200
    port: 8989
  - name: overseerr
    ip: 192.168.1.200
    port: 5055
  - name: server
    ip: 192.168.1.200
    port: 42069
  - name: ha
    ip: 192.168.1.187
    port: 8123
  - name: nzb
    ip: 192.168.1.200
    port: 6789
  - name: sab
    ip: 192.168.1.200
    port: 8282
  - name: tautulli
    ip: 192.168.1.200
    port: 8181
