apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatisch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automatisch
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: automatisch
    spec:
      containers:
        - name: automatisch
          env:
            - name: HOST
              value: "automate.rossreicks.com"
            - name: PROTOCOL
              value: "http"
            - name: PORT
              value: "3000"
            - name: APP_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "debug"
            - name: WEB_APP_URL
              value: "https://automate.rossreicks.com"
            - name: WEBHOOK_URL
              value: "https://automate.rossreicks.com"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: "postgres.local.rossreicks.com"
            - name: POSTGRES_DATABASE
              value: "automatisch"
            - name: POSTGRES_USERNAME
              value: "automatisch_user"
            - name: POSTGRES_PASSWORD
              value: "automatisch_pass"
          envFrom:
            - secretRef:
                name: automatisch-secrets
          image: rossreicks/automatisch:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: automatisch-data
              mountPath: /automatisch/storage
      volumes:
        - name: automatisch-data
          persistentVolumeClaim:
            claimName: automatisch-data-claim
      restartPolicy: Always
