apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: pihole-login-external-secret
  namespace: pihole
spec:
  organizationId: 4f7f686d-bd5a-4fe5-8b27-b1b3000f631d
  secretName: pihole-admin-secret
  map:
    - bwSecretId: 209f468e-56f9-4161-8212-b208017f5e1e
      secretKeyName: password
  authToken:
    secretName: bitwarden-access-token
    secretKey: token
