ingress:
  enabled: true
  hosts:
    - pihole.local.rossreicks.com

serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.80.82
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn"

serviceWeb:
  loadBalancerIP: 192.168.80.82
  type: ClusterIP

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 192.168.1.1
  - 1.1.1.1

admin:
  existingSecret: pihole-admin-secret
