ingress:
  enabled: true
  annotations:
      external-dns.alpha.kubernetes.io/hostname: pihole.rossreicks.com
      external-dns.alpha.kubernetes.io/target: home.rossreicks.com
  hosts:
    - pihole.rossreicks.com
  ingressClassName: nginx
  tls:
    disable: true

serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.80.82
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

persistentVolumeClaim:
  enabled: true

serviceWeb:
  type: ClusterIP

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 1.1.1.1

admin:
  existingSecret: pihole-admin-secret
