apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: mongodb-login-external-secret
spec:
  organizationId: 4f7f686d-bd5a-4fe5-8b27-b1b3000f631d
  secretName: mongodb-password
  map:
    - bwSecretId: 71467acf-1326-4f33-81cb-b1b701587173
      secretKeyName: MONGODB_PASS
  authToken:
    secretName: bitwarden-access-token
    secretKey: token
