- hosts: caddy_servers
  become: true
  tasks:
    - name: Get Ingress information from all namespaces
      kubernetes.core.k8s_info:
        api_version: networking.k8s.io/v1
        kind: Ingress
        all_namespaces: true
      register: ingresses

    - name: Template Caddyfile
      template:
        src: ansible/caddyfile.j2
        dest: /etc/caddy/Caddyfile
      vars:
        ingresses: "{{ ingresses.resources }}"
      notify: reload caddy

  handlers:
    - name: reload caddy
      systemd:
        name: caddy
        state: reloaded
