- hosts: caddy_servers
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Get Ingress information from specific namespaces
      kubernetes.core.k8s_info:
        api_version: networking.k8s.io/v1
        kind: Ingress
        namespace: "{{ item }}" # Iterate over namespaces
      loop: "{{ namespaces }}"
      register: namespace_ingresses

    - name: Flatten the list of ingresses
      set_fact:
        ingresses: "{{ namespace_ingresses.results | map(attribute='resources') | flatten }}"


    - name: Template Caddyfile
      template:
        src: ansible/caddyfile.j2
        dest: /etc/caddy/Caddyfile
      vars:
        ingresses: "{{ ingresses.resources }}"
      notify: reload caddy

  handlers:
    - name: reload caddy
      systemd:
        name: caddy
        state: reloaded
