- hosts: caddy_servers
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Template Caddyfile
      template:
        src: caddyfile.j2
        dest: /etc/caddy/Caddyfile
      environment:
        CLOUDFLARE_API_TOKEN: "{{ cloudflare_api_token }}"
      notify: reload caddy

  handlers:
    - name: reload caddy
      systemd:
        name: caddy
        state: reloaded
