version: "3.8"

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    restart: unless-stopped
    environment:
      OAUTH2_PROXY_PROVIDER: google
      OAUTH2_PROXY_REVERSE_PROXY: true
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: ${OAUTH2_PROXY_EMAIL_DOMAINS}
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_UPSTREAMS: "http://dummy:4181" # not used but required
      OAUTH2_PROXY_SET_BASIC_AUTH: "true"
      OAUTH2_PROXY_BASIC_AUTH_PASSWORD: ${OAUTH2_PROXY_BASIC_AUTH_PASSWORD}
      OAUTH2_PROXY_COOKIE_SECURE: "false" # ssl is handled by caddy
    ports:
      - "4180:4180"
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: America/Chicago
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - /config/pihole/etc-pihole:/etc/pihole
      - /config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  # cloudflare-ddns:
  #   container_name: cloudflare-ddns
  #   image: favonia/cloudflare-ddns:latest
  #   environment:
  #     - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
  #     - DOMAINS=home.rossreicks.com
  #     - PROXIED=false
  #   restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400
    restart: unless-stopped

  # backup ui
  backrest:
      image: garethgeorge/backrest:latest
      container_name: backrest
      volumes:
        - /config/backrest/data:/data
        - /config/backrest/config:/config
        - /config/backrest/cache:/cache
        - /datapool/backups/repos:/repos
      environment:
        - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
        - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
        - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
        - TZ=America/Chicago # set the timezone for the container, used as the timezone for cron jobs.
      restart: unless-stopped
      ports:
        - 9898:9898

  lunalytics:
      image: ksjaay/lunalytics:latest
      container_name: lunalytics
      ports:
        - 2308:2308
      volumes:
        - /config/lunalytics:/app/data
        - /config/lunalytics/logs:/app/logs
      restart: unless-stopped

  postgres:
    image: 'postgres:17'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - /config/postgres:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: 'redis:7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - /config/redis:/data
    networks:
      - internal

networks:
  internal:
