version: "3.8"

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    restart: unless-stopped
    environment:
      OAUTH2_PROXY_PROVIDER: google
      OAUTH2_PROXY_REVERSE_PROXY: true
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: ${OAUTH2_PROXY_EMAIL_DOMAINS}
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_UPSTREAMS: "http://dummy:4181" # not used but required
      OAUTH2_PROXY_SET_BASIC_AUTH: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_BASIC_AUTH_PASSWORD: ${OAUTH2_PROXY_BASIC_AUTH_PASSWORD}
      OAUTH2_PROXY_COOKIE_SECURE: "false" # ssl is handled by caddy
    ports:
      - "4180:4180"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: America/Chicago
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - ${CONFIG_PATH}/pihole/etc-pihole:/etc/pihole
      - ${CONFIG_PATH}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  # cloudflare-ddns:
  #   container_name: cloudflare-ddns
  #   image: favonia/cloudflare-ddns:latest
  #   environment:
  #     - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
  #     - DOMAINS=home.rossreicks.com
  #     - PROXIED=false
  #   restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400
    restart: unless-stopped

  # backup ui
  backrest:
      image: garethgeorge/backrest:latest
      container_name: backrest
      volumes:
        - ${CONFIG_PATH}:/hostconfig
        - ${CONFIG_PATH}/backrest/data:/data
        - ${CONFIG_PATH}/backrest/config:/config
        - ${CONFIG_PATH}/backrest/cache:/cache
        - ${NAS_PATH}/backups/repos:/repos
      environment:
        - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
        - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
        - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
        - TZ=America/Chicago # set the timezone for the container, used as the timezone for cron jobs.
      restart: unless-stopped
      ports:
        - 9898:9898

  lunalytics:
      image: ksjaay/lunalytics:latest
      container_name: lunalytics
      ports:
        - 2308:2308
      volumes:
        - ${CONFIG_PATH}/lunalytics:/app/data
        - ${CONFIG_PATH}/lunalytics/logs:/app/logs
      restart: unless-stopped

  postgres:
    image: 'postgres:17'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - ${CONFIG_PATH}/postgres:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: 'redis:7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/redis:/data
    networks:
      - internal

  # activepieces:
  #   image: ghcr.io/activepieces/activepieces:0.64.1
  #   container_name: activepieces
  #   restart: unless-stopped
  #   ## Enable the following line if you already use AP_EXECUTION_MODE with SANDBOXED or old activepieces, checking the breaking change documentation for more info.
  #   ## privileged: true
  #   ports:
  #     - '9654:80'
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     - AP_ENGINE_EXECUTABLE_PATH=dist/packages/engine/main.js
  #     - AP_API_KEY=${AP_API_KEY}
  #     - AP_ENCRYPTION_KEY=${AP_ENCRYPTION_KEY}
  #     - AP_JWT_SECRET=${AP_JWT_SECRET}
  #     - AP_ENVIRONMENT=prod
  #     - AP_FRONTEND_URL=https://activepieces.rossreicks.com
  #     - AP_WEBHOOK_TIMEOUT_SECONDS=30
  #     - AP_TRIGGER_DEFAULT_POLL_INTERVAL=5
  #     - AP_POSTGRES_DATABASE=activepieces
  #     - AP_POSTGRES_HOST=postgres
  #     - AP_POSTGRES_PORT=5432
  #     - AP_POSTGRES_USERNAME=${POSTGRES_USER}
  #     - AP_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - AP_EXECUTION_MODE=UNSANDBOXED
  #     - AP_REDIS_HOST=redis
  #     - AP_REDIS_PORT=6379
  #     - AP_FLOW_TIMEOUT_SECONDS=600
  #     - AP_TELEMETRY_ENABLED=true
  #     - AP_TEMPLATES_SOURCE_URL="https://cloud.activepieces.com/api/v1/flow-templates"
  #   volumes:
  #     - ${CONFIG_PATH}/activepieces:/usr/src/app/cache
  #   networks:
  #     - internal

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - internal
    depends_on:
      - redis

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    ports:
      - 9090:9090
    depends_on:
      - cadvisor

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: home-server
    restart: unless-stopped
    volumes:
      - ./alloy:/etc/alloy
      - ${CONFIG_PATH}/alloy:/var/lib/alloy/data
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /run/udev/data:/run/udev/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "12345:12345"
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    environment:
      - ALLOY_DEPLOY_MODE=docker
    user: "0:0"  # Run as root to access Docker socket and system metrics
    pid: host
    privileged: true

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ${CONFIG_PATH}/grafana:/var/lib/grafana
    user: "472:472"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}

logging:
  driver: loki
  options:
    loki-url: "http://host.docker.internal:3100/loki/api/v1/push"


networks:
  internal:
