apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: bazarr-config-claim
spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
