apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: automatisch-secrets
spec:
  organizationId: 4f7f686d-bd5a-4fe5-8b27-b1b3000f631d
  secretName: automatisch-secrets
  map:
    - bwSecretId: ea3fe58a-292a-4276-886c-b25d000ff1b4
      secretKeyName: APP_SECRET_KEY
    - bwSecretId: b45c454a-f661-4a3f-b0e8-b25d000f9957
      secretKeyName: ENCRYPTION_KEY
    - bwSecretId: 52c08ba6-1e99-48b3-a84b-b25d000fd4eb
      secretKeyName: WEBHOOK_SECRET_KEY
  authToken:
    secretName: bitwarden-access-token
    secretKey: token
