apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: automatisch-data-claim
spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
