name: Deploy Caddy

# on:
#     push:
#         branches: [main]

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - name: Run Ansible Playbook
              working-directory: ansible
              run: |
                  ansible-playbook deploy-caddy.yml -i inventory.ini -vvv -e "cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}"
